Spacy:
  processors: ["sentence", "tokenize", "pos", "ner", "umls_link"]
  lang: "en_ner_bionlp13cg_md"

Negation:
  negation_rules_path: ""

SRL:
  storage_path: "model/srl"
  batcher:
    batch_size: 1